language: ruby
bundler_args: --without development
before_install:
  - gem update --system 2.1.11
  - gem --version
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
notifications:
  email:
    - marcusmyers@gmail.com
env:
   - PUPPET_VERSION=3.3.2
   - PUPPET_VERSION=3.4.2
