language: ruby
rvm: 
   - 1.9.2
   - 1.9.3
notifications:
  email:
    - marcusmyers@gmail.com

env:
   - PUPPET_VERSION=3.0.2
   - PUPPET_VERSION=3.1.1
   - PUPPET_VERSION=3.2.4
   - PUPPET_VERSION=3.3.2
   - PUPPET_VERSION=3.4.2
