#!/bin/bash

/usr/bin/defaults write /Library/Preferences/com.apple.loginwindow LoginwindowText 'Property of Napoleon Area City Schools, if found call 419-599-7015'

touch /opt/NACSManage/logintext.txt
